name: afdian-sync

on:
  schedule: # Run workflow automatically
    - cron: '0 0/3 * * *' # 
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  call-afdian-action:
    name: Call reusable afdian action workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Call template afdian action workflow
        uses: LuoChu-NB2Dev/.github/.github/workflows/afdian-action.yml@master
        secrets:
          AFDIAN_USERID: ${{ secrets.AFDIAN_USERID }}
          AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}